### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by Charles-Hoot** [Rajeshwari-Rudra/GDP1#1]
Not sure that the TeamPlayer needs to have any date besides the invite date ( along with a joined flag.)

How do you find the locations that are associated with a competition?

**Comment by Vishalreddy114** [comment]
Team player will have a invited date and this will last for 3 days.If the team player will not respond to the mail within 3 days then the invitation will be closed.
The location in the quest can be accessed with the help of coordinates mainly the latitudes and longitudes.
