### ISSUE TITLE
Cost Estimates are confusing

### ISSUE THREAD

**Issue by Charles-Hoot** [Rajeshwari-Rudra/GDP1#12]
There are hours per week determined, but it doesn't look like they transferred correctly to the cost estimate. 

I appreciate the hourly billing rate being listed up front.

Without better numbers, I hesitate to look closer, but my sense is that you have not included enough time for implementation and testing.  I also wonder why you include iOS and Android implementations.  My sense is that those would be a follow-on implementation in the second semester.  I also don't think that you have budgeted enough time for it.

**Comment by nrajubn** [comment]
I have modified and corrected the error determined for hours per week and cost estimate.

I will be working on the implementation and testing of budget issues.

**Comment by nrajubn** [comment]
I have worked on the cost estimation and everything looks good
