### ISSUE TITLE
Admin Responsibilities

### ISSUE THREAD

**Issue by Charles-Hoot** [Rajeshwari-Rudra/GDP1#2]
authenticate and can authorize regarding this app  - what in particular?

**Comment by Rajeshwari-Rudra** [comment]
Admin validates the upcoming features of app and checks whether further modification is necessary or not? If so,then Admin give permissions to developers for further implementation of app.

**Comment by Rajeshwari-Rudra** [comment]
Thank You for your valuable feedback Dr.Hoot.
