### ISSUE TITLE
User Story 2 - clean up

### ISSUE THREAD

**Issue by Charles-Hoot** [Rajeshwari-Rudra/GDP1#5]
As a user I would like to create a new team where I am the captain.  I would like to be able to invite users by name and see if they have accepted my invitation.  I would like to be able to kick a player off of my team.

**Comment by Vishalreddy114** [comment]
A player can create a team and invite any number of players into the team. The invitation will stay active for three days. If the invited player does not accept it,then the person will be automatically rejected in the invitation.
