### ISSUE TITLE
Acceptance Criteria

### ISSUE THREAD

**Issue by Charles-Hoot** [Rajeshwari-Rudra/GDP1#6]
List the things that have to happen. Must be answerable with yes no or have a performance mark to meet.  "The app is fun to play" is not a good criteria.

1) User can create a team with a given name.
2) Team names with less than 5 characters are rejected.
3) User can invite players to the team.
4) Players can accept or reject invitation.
and so on (these are not to be taken as gospel)

**Comment by Puneeth159** [comment]
1. Yes, user can create a team with a given name.
2. No, team names will not be rejected with greater than 5 characters.
3. Yes, players can be invited by the user.
4. Yes, its players wish to accept or reject the invitation.

Thanks for your suggestion Dr. Charles Hoot.

**Comment by ghost** [comment]
1. Yes, a team can be registered with given name by the user.
2. No, characters with less than 5 of team names cannot be rejected.
3.  Yes, players can be invited to the team by the user.
4. Yes, players have an option to accept or reject the invitation.

Thank you for your suggestion Dr, Charles Hoot.
