### ISSUE TITLE
User Stories

### ISSUE THREAD

**Issue by Charles-Hoot** [Rajeshwari-Rudra/GDP1#7]
Most of them need work

For example
"As a backend developer, I would like to create the database by implementing entity-relationship, the backbone of the app." 

Is not a user story.

**Comment by Rajeshwari-Rudra** [comment]
Sure Dr.Hoot,will work on it and thank you for your suggestions.

**Comment by rohith0696** [comment]
Thanks Dr. Hoot for your suggestion. I have just resolved that issue.
